import type { Batch, Lead, Market, Segment, WorkspaceFocus } from "@/lib/types";

export const SAMPLE_FOCUS: WorkspaceFocus = {
  marketId: "leeds",
  segmentId: "leeds__local-service-businesses",
  batchId: "leeds__local-service-businesses__base-activa",
  city: "Leeds",
  niche: "Local service businesses",
  batchName: "Base activa",
  offerBaseId: "landing",
  offerAddons: [],
  offer: "Landing page",
  batchSize: 25,
};

const SAMPLE_DATE = "2026-03-17T12:00:00.000Z";

export const SAMPLE_MARKETS: Market[] = [
  {
    id: "leeds",
    name: "Leeds",
    description: "Mercado principal del dashboard demo.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
  {
    id: "bradford",
    name: "Bradford",
    description: "Mercado secundario para validar multi-ciudad.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
];

export const SAMPLE_SEGMENTS: Segment[] = [
  {
    id: "leeds__local-service-businesses",
    marketId: "leeds",
    name: "Local service businesses",
    description: "Vertical general para servicios locales.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
  {
    id: "leeds__legal-services",
    marketId: "leeds",
    name: "Legal services",
    description: "Despachos y oficinas legales.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
  {
    id: "bradford__healthcare",
    marketId: "bradford",
    name: "Healthcare",
    description: "Clinicas y practicas especializadas.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
];

export const SAMPLE_BATCHES: Batch[] = [
  {
    id: "leeds__local-service-businesses__base-activa",
    marketId: "leeds",
    segmentId: "leeds__local-service-businesses",
    name: "Base activa",
    source: "Demo import",
    importFileName: "data/leads-example.csv",
    status: "active",
    targetSize: 25,
    notes: "Lote de muestra con negocios de servicios locales.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
  {
    id: "leeds__legal-services__seguimiento-q1",
    marketId: "leeds",
    segmentId: "leeds__legal-services",
    name: "Seguimiento Q1",
    source: "Manual curation",
    importFileName: "",
    status: "active",
    targetSize: 18,
    notes: "Lote de abogados y firmas con oportunidades de rediseño.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
  {
    id: "bradford__healthcare__pilot-board",
    marketId: "bradford",
    segmentId: "bradford__healthcare",
    name: "Pilot board",
    source: "Demo import",
    importFileName: "",
    status: "active",
    targetSize: 12,
    notes: "Lote demo para validar expansion de ciudad.",
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
  },
];

export const SAMPLE_LEADS: Lead[] = [
  {
    id: "lead-1",
    marketId: "leeds",
    segmentId: "leeds__local-service-businesses",
    batchId: "leeds__local-service-businesses__base-activa",
    businessName: "Bella Nails Studio",
    city: "Leeds",
    niche: "Local service businesses",
    subniche: "Beauty salon",
    batchName: "Base activa",
    phone: "+44 113 555 0191",
    email: "hello@bellanails.co.uk",
    website: "",
    source: "Google Maps research",
    websiteStatus: "none",
    digitalPresence: "low",
    painPoints: ["No website", "No online booking", "Weak branding on socials"],
    offerType: "Landing + booking flow",
    stage: "qualified",
    opsStatus: "pending",
    notes: "Strong candidate for a before/after demo with online bookings.",
    lastTouch: "2026-03-16",
  },
  {
    id: "lead-2",
    marketId: "leeds",
    segmentId: "leeds__local-service-businesses",
    batchId: "leeds__local-service-businesses__base-activa",
    businessName: "Smile Dock Dental",
    city: "Leeds",
    niche: "Local service businesses",
    subniche: "Dental clinic",
    batchName: "Base activa",
    phone: "+44 113 555 0133",
    email: "frontdesk@smiledock.co.uk",
    website: "https://smiledock.co.uk",
    source: "Manual audit",
    websiteStatus: "weak",
    digitalPresence: "medium",
    painPoints: ["Site looks dated", "No WhatsApp CTA", "Homepage copy is generic"],
    offerType: "Website redesign + lead funnel",
    stage: "contacted",
    opsStatus: "contacted",
    notes: "Good fit for a redesign pitch with conversion review.",
    lastTouch: "2026-03-15",
  },
  {
    id: "lead-3",
    marketId: "leeds",
    segmentId: "leeds__local-service-businesses",
    batchId: "leeds__local-service-businesses__base-activa",
    businessName: "West Leeds Plumbing",
    city: "Leeds",
    niche: "Local service businesses",
    subniche: "Home services",
    batchName: "Base activa",
    phone: "+44 113 555 0187",
    email: "info@westleedsplumbing.uk",
    website: "https://westleedsplumbing.uk",
    source: "Referral list",
    websiteStatus: "weak",
    digitalPresence: "low",
    painPoints: ["Slow mobile site", "No quote form", "No clear trust signals"],
    offerType: "Landing + quote automation",
    stage: "booked",
    opsStatus: "booked",
    notes: "Booked call. Build a one-page service funnel before the meeting.",
    lastTouch: "2026-03-16",
  },
  {
    id: "lead-4",
    marketId: "leeds",
    segmentId: "leeds__legal-services",
    batchId: "leeds__legal-services__seguimiento-q1",
    businessName: "Oakwood Legal Services",
    city: "Leeds",
    niche: "Legal services",
    subniche: "Legal office",
    batchName: "Seguimiento Q1",
    phone: "+44 113 555 0119",
    email: "contact@oakwoodlegal.uk",
    website: "https://oakwoodlegal.uk",
    source: "Google Maps research",
    websiteStatus: "weak",
    digitalPresence: "high",
    painPoints: ["Old site structure", "Weak call flow", "No lead qualification"],
    offerType: "Website refresh + intake automation",
    stage: "demo",
    opsStatus: "interested",
    notes: "High-value lead. Needs a polished PDF and demo script.",
    lastTouch: "2026-03-14",
  },
  {
    id: "lead-5",
    marketId: "bradford",
    segmentId: "bradford__healthcare",
    batchId: "bradford__healthcare__pilot-board",
    businessName: "AireFit Physio",
    city: "Bradford",
    niche: "Healthcare",
    subniche: "Physiotherapy clinic",
    batchName: "Pilot board",
    phone: "+44 1274 555 019",
    email: "bookings@airefit.co.uk",
    website: "https://airefit.co.uk",
    source: "Manual audit",
    websiteStatus: "strong",
    digitalPresence: "medium",
    painPoints: ["Weak landing copy", "No retargeting flow"],
    offerType: "Campaign landing + nurture sequence",
    stage: "proposal",
    opsStatus: "interested",
    notes: "Proposal pending. Offer monthly growth support after launch.",
    lastTouch: "2026-03-13",
  },
];
